### ISSUE TITLE
// site owner // het bestelproces alleen toegankelijk maken voor klanten met een toegangscode // controle houd over het aantal te bestellen items

### ISSUE THREAD

**Issue by martijnmajoor** [martijnmajoor/love#12]
DoD: Gebruikers kunnen enkel bestellen als zij een geldige toegangscode hebben.
DoD: De code blijft geldig zolang de gebruiker nog niet besteld heeft.
DoD: Na bestelling wordt de code inactief gemaakt.

**Comment by martijnmajoor** [comment]
Zie optie 2 bij: http://www.wpmayor.com/members-only-woocommerce-store/

tl;dr: Mogelijk op te lossen door gebruik te maken van plugins. Waarschijnlijk wel tijdsintensief om te implementeren, bovendien onzeker of dit 100% overeenkomt met onze functionele eisen.

Overweeg nog steeds om zelf een login-systeem te maken. Uitzoeken hoeveel tijd dat zou kosten.

**Comment by michielwoerkom** [comment]
@martijnmajoor Wellicht kunnen we nadenken of het een idee is dat jij dan de login etc. maakt en ik de front-end maak.. dus zonder WP enzo. Wellicht kunnen we daarvoor een plan maken wellicht Laravel & Angular gebruiken ofzo..? Terwijl Daan uit zn neus eet.

**Comment by martijnmajoor** [comment]
Gefixt, custom checkout field aangemaakt in WooCommerce. Gebruik dit SQL script om de tabel te maken:

CREATE TABLE `stl_invitation_codes` (
  `id` int(11) NOT NULL,
  `code` varchar(20) NOT NULL,
  `redeemed` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
